# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc69ffa027672cdc4311f317e9a71a917c67ccda2f105eb44d5b3ed304d06ae6ff07ec037c5ab246642c11c577c6a2acc69ec5898b93ebdda0aee30ee0d0216a

test:
  secret_key_base: e71915683471442a54a317213acf401f8b06570103fdd8cf2ea223a97f00b471ab1553131a98148b3afa15bd1c5f6fe7be04bd184ef979d9a049466255529353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
